# 根据动画实测，动画持续4秒
operations:
  - op_name: "设置状态"
    state: "自定义-失衡时间"
    seconds_add: -3.2
  # 终结技动画期间, 失衡不会动
  - op_name: "设置状态"
    state: "自定义-动作不打断"
    seconds: 4
  - op_name: "设置状态"
    state: "自定义-叶瞬光-在天"
  - op_name: "设置状态"
    state: "自定义-无视闪光"
    seconds: 15
  - op_name: "按键-终结技"
    post_delay: 0.1
    repeat: 20
  - op_name: "按键-切换角色"
    agent_name: "叶瞬光"
  - op_name: "按键-终结技"
    post_delay: 0.1
    repeat: 10
  - op_name: "等待秒数"
    seconds: 1
