# 根据动画实测
operations:
  # 上弹
  - op_name: "按键-移动-前-按下"
  - op_name: "等待秒数"
    seconds: 0.01
  - op_name: "按键-闪避-按下"
  - op_name: "等待秒数"
    seconds: 0.1
  - op_name: "按键-闪避-松开"
  # 输出
  - op_name: "按键-普通攻击"
    post_delay: 0.1
    repeat: 8
  - op_name: "等待秒数"
    seconds: 0.2
  - op_name: "按键-移动-前-松开"