# 暂定2秒，待实测调整
operations:
  - op_name: "设置状态"
    state_list: ["自定义-动作不打断", "自定义-无视闪光"]
    seconds: 10
  - op_name: "设置状态"
    state: "自定义-失衡时间"
    seconds_add: -1
  - op_name: "设置状态"
    state: "自定义-动作不打断"
    seconds: 2
  - op_name: "等待秒数"
    seconds: 2
