operations:
  - op_name: "等待秒数"
    seconds: 0.5
  - op_name: "设置状态"
    state: "自定义-失衡时间"
  - op_name: "按键-连携技-取消-按下"
  - op_name: "等待秒数"
    seconds: 0.1
  - op_name: "按键-连携技-取消-松开"
  - op_name: "等待秒数"
    seconds: 0.1
  - op_name: "按键-连携技-取消-按下"
  - op_name: "等待秒数"
    seconds: 0.1
  - op_name: "按键-连携技-取消-按下"
  - op_name: "等待秒数"
    seconds: 0.1
  - op_name: "设置状态"
    state: "自定义-连携取消"
