template_name: "卢西娅-暗破检测"
handlers:
  - states: "[卢西娅-特殊技可用] & ![自定义-卢西娅-暗破,0,20]"
    debug_name: "卢西娅进场先开暗破"
    operations:
      - op_name: "按键-切换角色"
        agent_name: "卢西娅"
      - operation_template: "卢西娅-强化特殊技合轴"