template_name: "特殊情况-紧急切人"
handlers:
  - states: "[自定义-琉音-投诉]{3,99} & [自定义-失衡时间,-10,15]"
    debug_name: "失衡被琉音延长了"
    operations:
      - op_name: "设置状态"
        state: "自定义-失衡时间"
        seconds_add: -2

  #清理假音连携
  - states: "[自定义-失衡时间, 1.5, 99] & [自定义-非失衡连携, 0, 99]{0, 0} & ![按键可用-连携技, 0, 12]"
    debug_name: "清理非失衡连携"
    operations:
      - op_name: "清除状态"
        state: "自定义-非失衡连携"
      - op_name: "清除状态"
        state: "自定义-失衡时间"

  #清理跳过
  - states: "[自定义-连携跳过, 3, 999]"
    debug_name: "清理连携跳过状态"
    operations:
      - op_name: "清除状态"
        state: "自定义-连携跳过"

  # 嘉音放大招和补唱歌, 至少3分钟一次
  - states: "![前台-耀嘉音]"
    interrupt_states: "[前台-能量, 0, 0.1] & ![前台-耀嘉音] & ([按键-切换角色-下一个, 0.3, 1] | [按键-切换角色-上一个, 0.3, 1])"
    debug_name: "耀嘉音状态检查"
    sub_handlers:
      - states: "[耀嘉音-终结技可用] & ![自定义-失衡时间, -10, 10]"
        debug_name: "切耀嘉音放大招"
        operations:
          - op_name: "按键-切换角色"
            agent_name: "耀嘉音"
          - op_name: "等待秒数"
            seconds: 0.5
          - operation_template: "耀嘉音-终结技"
          - op_name: "等待秒数"
            seconds: 0.2
          - op_name: "设置状态"
            state: "自定义-非失衡连携"
            add: 2

      - states: "[后台-耀嘉音] & ![前台-耀嘉音] & ![自定义-耀嘉音-唱歌, 0, 180]"
        debug_name: "耀嘉音补唱歌"
        operations:
          - op_name: "按键-切换角色"
            agent_name: "耀嘉音"
          - op_name: "按键-移动-前-按下"
          - op_name: "按键-特殊攻击"
            post_delay: 0.1
            repeat: 3

  # 我看啊，是放错了终结技
  - states: "[自定义-耀嘉音-尝试释放终结技, 2, 99] & [耀嘉音-终结技可用]"
    debug_name: "终结技放错了！"
    operations:
      - op_name: "清除状态"
        state: "自定义-耀嘉音-尝试释放终结技"
      - op_name: "清除状态"
        state: "自定义-非失衡连携"

  - states: "([前台-强攻] | [前台-命破])"
    interrupt_states: "[前台-能量, 0, 0.1] & ![前台-琉音] & ([按键-切换角色-下一个, 0.3, 1] | [按键-切换角色-上一个, 0.3, 1])"
    debug_name: "琉音状态检查"
    sub_handlers:
      - state_template: "琉音-送客决策"
      - states: "([琉音-终结技可用] & ![自定义-失衡时间, -10, 12])"
        debug_name: "琉音终结技"
        operations:
          - op_name: "等待秒数"
            seconds: 0.5
          - op_name: "按键-切换角色"
            agent_name: "琉音"
          - op_name: "等待秒数"
            seconds: 0.2
          - operation_template: "琉音-终结技"

  # 青衣在失衡其间不小心切出来了就切到输出去
  - states: "[前台-青衣] & [自定义-失衡时间, 0, 10]"
    debug_name: "青衣失衡离场"
    sub_handlers:
      - states: "[后台-2-强攻] | [后台-2-异常] | [后台-2-命破]"
        debug_name: "切换上位输出"
        operations:
          - op_name: "按键-切换角色-上一个"

      - states: "[后台-1-强攻] | [后台-1-异常]| [后台-1-命破]"
        debug_name: "切换下位输出"
        operations:
          - op_name: "按键-切换角色-下一个"

  #零号安比的追击白银点
  - states: "[零号安比-能量] & ![自定义-零号安比-追击回能, 0, 5] & ([后台-扳机] | [后台-奥菲丝] | [后台-波可娜])"
    debug_name: "零号安比追击回能"
    operations:
      - op_name: "设置状态"
        state: "自定义-零号安比-白雷"
        add: 200
      - op_name: "设置状态"
        state: "自定义-零号安比-追击回能"

  # 特殊处理，注意这里要等一秒，这样每次切人之后优先至少做一次角色模板里的动作，防止循环切人
  # 没有比掉血更特殊的，掉血了就不要进来切人了
  - states: "![自定义-非失衡连携, 0, 99] & ![自定义-血量扣减, 0, 1] & !([按键-切换角色-下一个, 0, 1]|[按键-切换角色-上一个, 0, 1])"
    debug_name: "紧急切人检查"
    sub_handlers:
      - states: "![自定义-动作不打断, -10, 0]"
        debug_name: "不打断动作切人"
        sub_handlers:
          - states: ""
            debug_name: "开局紧急补BUFF"
            sub_handlers:
              - states: "![前台-露西] & [露西-特殊技可用] & ![自定义-露西-加油, 0, 30] & ![自定义-失衡时间, 0, 10]"
                debug_name: "露西补BUFF"
                operations:
                  - op_name: "按键-切换角色"
                    agent_name: "露西"
                  - operation_template: "露西-高飞球合轴"

              - states: "![前台-苍角] & ![自定义-苍角-展旗, 0, 30] & [苍角-能量]{00, 120} & ![自定义-失衡时间, 0, 10]"
                debug_name: "苍角展旗"
                operations:
                  - op_name: "按键-切换角色"
                    agent_name: "苍角"
                  - op_name: "等待秒数"
                    seconds: 0.3
                  - operation_template: "苍角-1E展旗合轴"

              - state_template: "奥菲丝-强特决策"
              - state_template: "琉音-刷好评"
              - state_template: "卢西娅-暗破检测"

              - states: "[潘引壶-特殊技可用] & ![自定义-潘引壶-通窍, 0, 10]"
                debug_name: "潘引壶先来个降龙十八掌"
                operations:
                  - op_name: "按键-切换角色"
                    agent_name: "潘引壶"
                  - operation_template: "潘引壶-特殊攻击合轴"

              - states: "![前台-扳机] & [扳机-能量]{0, 120} & ![扳机-绝意]{10,999} & ![自定义-失衡时间, 0, 20]"
                debug_name: "扳机紧急切人"
                operations:
                  - op_name: "按键-切换角色"
                    agent_name: "扳机"

              - states: "[后台-浮波柚叶] & ![自定义-浮波柚叶-狸之愿, 0, 40]"
                debug_name: "柚叶补BUFF"
                sub_handlers:
                  - states: "[浮波柚叶-特殊技可用]"
                    operations:
                    - op_name: "按键-切换角色"
                      agent_name: "浮波柚叶"
                    - operation_template: "浮波柚叶-强化特殊技合轴"

                  - states: "[浮波柚叶-终结技可用]"
                    operations:
                    - op_name: "按键-切换角色"
                      agent_name: "浮波柚叶"
                    - operation_template: "浮波柚叶-终结技"

              - states: "![前台-丽娜] & [丽娜-能量]{60, 120} & ![自定义-丽娜-人偶, -30, 0]"
                debug_name: "丽娜召唤人偶"
                operations:
                  - op_name: "设置状态"
                    state: "自定义-丽娜-人偶"
                    seconds: 14
                  - op_name: "按键-切换角色"
                    agent_name: "丽娜"
                  - op_name: "按键-特殊攻击"
                    post_delay: 0.1
                    repeat: 4
                  - operation_template: "通用-切人普通攻击"

          - states: ""
            debug_name: "紧急补buff"
            sub_handlers:
              # 挨打了或者没盾了补盾
              - states: "![前台-凯撒] & [凯撒-特殊技可用] & ([自定义-血量扣减, 0, 3] | ![自定义-凯撒-护盾, 0, 30])"
                debug_name: "凯撒补盾"
                operations:
                  - op_name: "按键-切换角色"
                    agent_name: "凯撒"
                  - op_name: "清除状态"
                    state_list: ["自定义-血量扣减"]

              - states: "![前台-照] & ![自定义-照-蓄力中,0,10]"
                debug_name: "照紧急切入"
                sub_handlers:
                  - states: "[照-霜寒值]{100, 100}"
                    debug_name: "照满霜寒值-登场技"
                    operations:
                      - op_name: "按键-切换角色"
                        agent_name: "照"
                      - op_name: "设置状态"
                        state: "自定义-照-蓄力中"
                      - operation_template: "照-登场技"

                  - states: "[照-特殊技可用] & [照-霜寒值]{0, 80} & ![自定义-失衡时间, 0, 10]"
                    debug_name: "照有强化特殊技"
                    operations:
                      - op_name: "按键-切换角色"
                        agent_name: "照"
                      - op_name: "设置状态"
                        state: "自定义-照-蓄力中"
                      - operation_template: "照-强化特殊攻击"

                  - states: "[照-终结技可用] & [照-霜寒值]{0, 80} & ![自定义-失衡时间, 0, 10]"
                    debug_name: "照有终结技"
                    operations:
                      - op_name: "按键-切换角色"
                        agent_name: "照"
                      - op_name: "设置状态"
                        state: "自定义-照-蓄力中"
                      - operation_template: "照-终结技"

              # 千夏紧急切入
              - states: "![前台-千夏]"
                debug_name: "千夏紧急切入"
                sub_handlers:
                  - states: "[千夏-特殊技可用] & ![自定义-失衡时间, 0, 10]"
                    debug_name: "千夏有特殊技"
                    operations:
                      - op_name: "按键-切换角色"
                        agent_name: "千夏"
                      - operation_template: "千夏-特殊攻击"

                  - states: "[千夏-终结技可用] & ![自定义-失衡时间, 0, 10]"
                    debug_name: "千夏有终结技"
                    operations:
                      - op_name: "按键-切换角色"
                        agent_name: "千夏"
                      - operation_template: "通用-终结技"

              # 星见雅 能量和落霜判断
              - states: "([雅-能量]{80, 999} | ([雅-能量]{40, 999} & [雅-落霜]{2, 6})) & ![前台-雅] & ![前台-支援]"
                debug_name: "雅能量豆数切入"
                operations:
                  - op_name: "按键-切换角色"
                    agent_name: "雅"

              # 队伍里有青衣，切过去打击破
              - states: "[青衣-能量]{0, 120} & ![自定义-失衡时间, -10, 12] & ![自定义-黄光切人, 0, 2.5] & ![前台-青衣] & ![前台-仪玄]"
                debug_name: "青衣击破准备"
                operations:
                  - op_name: "按键-切换角色"
                    agent_name: "青衣"

              - states: "([妮可-特殊技可用] | [妮可-终结技可用])  & ![自定义-妮可-能量场, -15, 3.5] & ![前台-妮可]"
                debug_name: "失衡期补能量场"
                sub_handlers:
                  # 妮可失衡期间切到妮可，这里的-15，3.5意思是妮可BUFF是倒数制
                  - states: "[自定义-失衡时间, 5, 10]"
                    debug_name: "失衡期补能量场"
                    operations:
                      - op_name: "按键-切换角色"
                        agent_name: "妮可"

          - states: "[前台-击破] & ![自定义-合轴时间, 0, 30] & [自定义-失衡时间, 0, 10]"
            debug_name: "击破连携检查"
            sub_handlers:
              - states: "[后台-1-强攻] | [后台-2-强攻] | [后台-1-异常] | [后台-2-异常] | [后台-1-命破] | [后台-2-命破]"
                debug_name: "击破后切输出"
                operations:
                  - op_name: "按键-特殊攻击"
                    post_delay: 0.2
                    repeat: 1
                  - op_name: "设置状态"
                    state: "自定义-合轴时间"
                  - op_name: "按键-特殊攻击"
                    post_delay: 0.2
                    repeat: 1

      - states: "" # 可以打断动作的
        debug_name: "可打断动作检查"
        sub_handlers:
          - states: "([妮可-特殊技可用] | [妮可-终结技可用])  & ![自定义-妮可-能量场, -15, 3.5] & ![前台-妮可]"
            debug_name: "妮可能量场准备"
            sub_handlers:
              - states: "[前台-零号安比] & [自定义-零号安比-白雷, 0, 99]{300, 999}" # 零号安比爆发前补状态
                debug_name: "零号安比爆发前补状态"
                operations:
                  - op_name: "按键-切换角色"
                    agent_name: "妮可"
