template_name: "速切模板-希希芙"
handlers:
  - states: "[前台-希希芙]"
    interrupt_states: "[前台-能量, 0, 0.1] & ![前台-希希芙]"
    sub_handlers:
      - states: "[自定义-终结技被强制释放, 0, 1]"
        operations:
          - operation_template: "希希芙-终结技"

      - states: "[自定义-黄光切人, 0, 1]"
        operations:
          - operation_template: "希希芙-支援攻击"

      - states: "[自定义-红光闪避, 0, 1]"
        operations:
          - operation_template: "希希芙-闪A"

      - states: "[自定义-连携换人, 0, 0.5]"
        operations:
          - operation_template: "希希芙-连携攻击"

      - states: "([按键-切换角色-下一个, 0, 0.3]|[按键-切换角色-上一个, 0, 0.3])"
        debug_name: "切人后等待"
        sub_handlers:
          - states: "[自定义-快速支援换人, 0, 0.5]"
            operations:
              - operation_template: "通用-快速支援"
          - states: ""
            operations:
              - op_name: "等待秒数"
                seconds: 0.3

      - states: "[自定义-希希芙-毒素]{6, 999}"
        debug_name: "希希芙-满毒素长按"
        operations:
          - operation_template: "希希芙-长按普攻"

      - states: "[希希芙-终结技可用]"
        debug_name: "希希芙-终结技"
        operations:
          - operation_template: "希希芙-终结技"

      - states: "[希希芙-特殊技可用]"
        debug_name: "希希芙-EA"
        operations:
          - operation_template: "希希芙-EA"

      - states: ""
        debug_name: "希希芙-默认普攻"
        operations:
          - operation_template: "希希芙-普通普攻"
