template_name: "速切模板-维琳娜"
handlers:
  - states: "[前台-维琳娜]"
    interrupt_states: "[前台-能量, 0, 0.1] & ![前台-维琳娜]"
    sub_handlers:
      - states: "[自定义-终结技被强制释放, 0, 1]"
        operations:
          - operation_template: "维琳娜-终结技"

      - states: "[自定义-红光闪避, 0, 1]"
        sub_handlers:
          - states: "[维琳娜-特殊技可用]"
            debug_name: "红光特殊技"
            operations:
              - operation_template: "维琳娜-特殊攻击"
          - states: ""
            debug_name: "红光闪A"
            operations:
              - operation_template: "维琳娜-闪A"

      - states: "[自定义-黄光切人, 0, 1]"
        operations:
          - operation_template: "维琳娜-支援攻击"

      - states: "[自定义-连携换人, 0, 0.5]"
        operations:
          - operation_template: "维琳娜-连携攻击"

      - states: "([按键-切换角色-下一个, 0, 0.3]|[按键-切换角色-上一个, 0, 0.3])"
        debug_name: "切人后等待"
        operations:
          - op_name: "等待秒数"
            seconds: 0.3

      - states: "[按键可用-快速支援]"
        debug_name: "动作有问题，需要狂点"
        operations:
          - op_name: "按键-快速支援"
          - op_name: "等待秒数"
            seconds: 0.1

      - states: "[维琳娜-终结技可用]"
        interrupt_states: "[按键可用-快速支援]"  # 不可用时打断
        debug_name: "开大招了"
        operations:
          - operation_template: "维琳娜-终结技"

      - states: "[维琳娜-风华]{85,135}"
        debug_name: "高风华长按普攻"
        operations:
          - operation_template: "维琳娜-长按普攻"

      - states: "[维琳娜-特殊技可用] & [维琳娜-风华]{0,84}"
        debug_name: "低风华强化特殊技合轴"
        operations:
          - operation_template: "维琳娜-强化特殊技合轴"

      - states: ""
        debug_name: "普通攻击"
        operations:
          - operation_template: "维琳娜-普通攻击"
          - op_name: "设置状态"
            state: "自定义-合轴时间"
