# 耀嘉音的上一位和下一位无法识别, 这非常无解

template_name: "速切模板-耀嘉音"
handlers:
  - states: "[前台-耀嘉音]"
    interrupt_states: "[前台-能量, 0, 0.1] & ![前台-耀嘉音]"
    sub_handlers:
      - states: "[自定义-终结技被强制释放, 0, 1]"
        operations:
          - operation_template: "耀嘉音-终结技"

      - states: "[耀嘉音-终结技可用]"
        operations:
          - op_name: "设置状态"
            state: "自定义-耀嘉音-尝试释放终结技"
          - operation_template: "耀嘉音-终结技"
          - op_name: "设置状态"
            state: "自定义-非失衡连携"
            add: 2

      - states: "![按键可用-快速支援, 0, 1]"
        operations:
          - operation_template: "耀嘉音-强化特殊技"
