template_name: "速切模板-爱芮"
handlers:
  - states: "[前台-爱芮]"
    interrupt_states: "[前台-能量, 0, 0.1] & ![前台-爱芮]"
    sub_handlers:
      - states: "[自定义-终结技被强制释放, 0, 1]"
        operations:
          - operation_template: "爱芮-终结技"

      # 黄光入场
      - states: "[自定义-黄光切人, 0, 1]"
        operations:
          - operation_template: "爱芮-支援攻击"

      # 红光
      - states: "[自定义-红光闪避, 0, 1]"
        operations:
          - operation_template: "爱芮-闪A"

      # 连携
      - states: "[自定义-连携换人, 0, 0.5]"
        operations:
          - operation_template: "爱芮-连携攻击"

      # 切人后等待
      - states: "([按键-切换角色-下一个, 0, 0.3]|[按键-切换角色-上一个, 0, 0.3])"
        debug_name: "切人后等待"
        sub_handlers:
          - states: "[按键可用-快速支援, 0, 0.5]"
            operations:
              - op_name: "等待秒数"
                seconds: 1.0
          - states: ""
            operations:
              - op_name: "等待秒数"
                seconds: 0.3

      # 失衡期间：开大 → 0~2点特殊技，7点以上长按，其他普攻
      - states: "[自定义-失衡时间, -5, 15]"
        sub_handlers:
          - states: "[爱芮-终结技可用]"
            debug_name: "失衡期终结技"
            operations:
              - operation_template: "爱芮-终结技"

          - states: "[爱芮-应援能量]{0, 2} & [爱芮-特殊技可用]"
            debug_name: "失衡期0~2点开特殊技"
            operations:
              - operation_template: "爱芮-强化特殊技"

          - states: "[爱芮-应援能量]{6, 8}"
            interrupt_states: "[爱芮-应援能量]{0, 1}"
            debug_name: "失衡期7点以上长按"
            operations:
              - operation_template: "爱芮-长按攻击"

          - states: ""
            debug_name: "失衡期普攻"
            operations:
              - operation_template: "爱芮-普通攻击"

      # 非失衡期间
      - states: ""
        sub_handlers:
          # 无击破时直接开大，有击破时等失衡
          - states: "[爱芮-终结技可用] & ![后台-1-击破] & ![后台-2-击破]"
            debug_name: "无击破直接开大"
            operations:
              - operation_template: "爱芮-终结技"

          # 7点以上长按
          - states: "[爱芮-应援能量]{6, 8}"
            interrupt_states: "[爱芮-应援能量]{0, 1}"
            debug_name: "7点以上长按"
            operations:
              - operation_template: "爱芮-长按攻击"

          # 能量满120，防止溢出，必须放特殊技
          - states: "[爱芮-能量]{120, 120} & [爱芮-特殊技可用]"
            debug_name: "能量满120放特殊技"
            operations:
              - operation_template: "爱芮-强化特殊技"

          # 0~2点特殊技可用就放（不管有没有击破）
          - states: "[爱芮-应援能量]{0, 2} & [爱芮-特殊技可用]"
            debug_name: "0~2点放特殊技"
            operations:
              - operation_template: "爱芮-强化特殊技"

          # 默认普攻
          - states: ""
            debug_name: "普攻"
            operations:
              - operation_template: "爱芮-普通攻击"