template_name: "速切模板-爱丽丝"
handlers:
  - states: "[前台-爱丽丝]"
    interrupt_states: "[前台-能量, 0, 0.1] & ![前台-爱丽丝]"
    sub_handlers:
      - states: "[自定义-终结技被强制释放, 0, 1]"
        operations:
          - operation_template: "爱丽丝-终结技"

      # 支援
      - states: "[自定义-黄光切人, 0, 1]"
        operations:
          - operation_template: "爱丽丝-支援攻击"

      - states: "[自定义-红光闪避, 0, 1]"
        operations:
          - operation_template: "爱丽丝-闪A"

      # 连携
      - states: "[自定义-连携换人, 0, 0.5]"
        operations:
          - operation_template: "爱丽丝-连携攻击"

      # 防呆
      - states: "([按键-切换角色-下一个, 0, 0.3]|[按键-切换角色-上一个, 0, 0.3])"
        debug_name: "切人后等待"
        sub_handlers:
          - states: "[自定义-快速支援换人, 0, 0.1]"
            operations:
              - op_name: "等待秒数"
                seconds: 0.1
          - states: ""
            operations:
              - op_name: "等待秒数"
                seconds: 0.1

      - states: "[爱丽丝-剑仪]{300, 300}"
        interrupt_states: "[爱丽丝-剑仪]{0, 0}"
        operations:
          - operation_template: "爱丽丝-长按普攻合轴"

      - states: "[自定义-爱丽丝-蓄力中, -5, 0]"
        operations:
          - op_name: "设置状态"
            state_list: ["自定义-合轴时间"]

      # 终结技时刻，需要注意出场第一秒可能识别错误
      - states: "[爱丽丝-终结技可用] & [爱丽丝-剑仪]{0, 100}"
        operations:
          - operation_template: "爱丽丝-终结技"

      - states: "[爱丽丝-特殊技可用]"
        operations:
          - operation_template: "爱丽丝-强化特殊技"

      - states: ""
        interrupt_states: "[爱丽丝-剑仪]{300, 300} | [爱丽丝-特殊技可用] | ([爱丽丝-终结技可用] & [爱丽丝-剑仪]{0, 100})"
        operations:
          - operation_template: "爱丽丝-普通攻击"
