template_name: "速切模板-叶瞬光"
handlers:
  - states: "[前台-叶瞬光]"
    interrupt_states: "[前台-能量, 0, 0.1] & ![前台-叶瞬光]"
    sub_handlers:
      - states: "[自定义-黄光切人, 0, 1]"
        operations:
          - operation_template: "叶瞬光-支援攻击"

      - states: "[自定义-红光闪避, 0, 1] & [叶瞬光-明心境]{0,0}"
        operations:
          - operation_template: "叶瞬光-格挡"

      - states: "[自定义-连携换人, 0, 1]"
        sub_handlers:
          - states: "[叶瞬光-明心境]{1,120}"
            interrupt_states: "[叶瞬光-明心境]{0,0}"
            operations:
              - op_name: "设置状态"
                state: "自定义-无视闪光"
                seconds: 10
              - op_name: "等待秒数"
                seconds: 3
              - op_name: "设置状态"
                state: "自定义-叶瞬光-在天"
          - states: "[叶瞬光-明心境]{0,0}"
            interrupt_states: "[叶瞬光-明心境]{1,120}"
            operations:
              - operation_template: "叶瞬光-连携攻击"

      # 防呆
      - states: "([按键-切换角色-下一个, 0, 0.3]|[按键-切换角色-上一个, 0, 0.3])"
        debug_name: "切人后等待"
        sub_handlers:
          - states: "[叶瞬光-终结技可用] & [叶瞬光-青溟剑势-红]{0,3}"
            interrupt_states: "[叶瞬光-明心境]{1,120}"
            operations:
              - operation_template: "叶瞬光-终结技-起"

          - states: "[叶瞬光-明心境]{1,120}"
            interrupt_states: "[叶瞬光-明心境]{0,0}"
            operations:
              - op_name: "设置状态"
                state: "自定义-叶瞬光-在地"
              - op_name: "等待秒数"
                seconds: 0.3

          - states: "[按键可用-快速支援, 0, 0.3]"
            operations:
              - op_name: "等待秒数"
                seconds: 0.3

          - states: ""
            operations:
              - op_name: "等待秒数"
                seconds: 0.3

      - states: "[自定义-终结技被强制释放, 0, 1] & [叶瞬光-常态]{1,1} & [叶瞬光-明心境]{0,0}  & ![自定义-无视闪光, -15, 0] & [叶瞬光-能量]{10,120} & [叶瞬光-终结技可用]"
        interrupt_states: "[叶瞬光-常态]{0,0}"
        operations:
          - operation_template: "叶瞬光-终结技-起"

      - states: "[叶瞬光-常态]{1,1} & [叶瞬光-明心境]{0,0} "
        interrupt_states: "[叶瞬光-常态]{0,0} & ![叶瞬光-明心境]{0,0}"
        debug_name: "常态-技能优先"
        sub_handlers:
          - states: "[自定义-无视闪光, -15, 0] & [自定义-动作不打断, -15, 0]"
            operations:
              - op_name: "清除状态"
                state: "自定义-合轴时间"
              - op_name: "清除状态"
                state: "自定义-动作不打断"

          - states: "[叶瞬光-青溟剑势-红]{6,6}"
            operations:
              - op_name: "设置状态"
                state: "自定义-合轴时间"
              - op_name: "等待秒数"
                seconds: 0.1
              - op_name: "设置状态"
                state: "自定义-无视闪光"
                seconds: 10
              - operation_template: "叶瞬光-变身"

          - states: "[叶瞬光-终结技可用] & [叶瞬光-青溟剑势-红]{0,5}"
            operations:
              - operation_template: "叶瞬光-终结技-起"

          - states: "[叶瞬光-特殊技可用]"
            operations:
              - op_name: "清除状态"
                state: "自定义-无视闪光"
              - operation_template: "叶瞬光-强化特殊攻击"

          - states: ""
            interrupt_states: "[叶瞬光-终结技可用] | [叶瞬光-特殊技可用] | [叶瞬光-青溟剑势-红]{6,6}"
            operations:
              - op_name: "清除状态"
                state: "自定义-无视闪光"
              - operation_template: "叶瞬光-普通攻击"

      - states: "[叶瞬光-常态]{0,0} & [叶瞬光-明心境]{0,0}"
        debug_name: "合轴"
        operations:
        - op_name: "清除状态"
          state: "自定义-无视闪光"
        - op_name: "清除状态"
          state: "自定义-动作不打断"
        - op_name: "设置状态"
          state: "自定义-合轴时间"
        - op_name: "等待秒数"
          seconds: 0.1

      - states: "[叶瞬光-常态]{0,0} & ![叶瞬光-明心境]{0,0}"
        interrupt_states: "[叶瞬光-明心境]{0,0}"
        debug_name: "明心境-期间输出"
        sub_handlers:
          - states: "[叶瞬光-明心境]{110,120}"
            interrupt_states: "[叶瞬光-明心境]{0,118}"
            debug_name: "等待变身就绪"
            operations:
              - op_name: "设置状态"
                state: "自定义-无视闪光"
                seconds: 9
              - op_name: "设置状态"
                state: "自定义-动作不打断"
                seconds: 9
              - op_name: "按键-特殊攻击-松开"
              - op_name: "按键-普通攻击"
                post_delay: 0.1
                repeat: 40

      - states: "[叶瞬光-明心境]{20,120}"
        interrupt_states: "[叶瞬光-明心境]{0,20}"
        debug_name: "明心境-输出"
        sub_handlers:
          - states: "[叶瞬光-青溟剑势-白]{6,6}"
            interrupt_states: "[叶瞬光-青溟剑势-白]{4,4}"
            operations:
              - op_name: "设置状态"
                state: "自定义-无视闪光"
                seconds: 9
              - op_name: "设置状态"
                state: "自定义-动作不打断"
                seconds: 9
              - op_name: "按键-特殊攻击"
                post_delay: 0.1
                repeat: 10
              - op_name: "按键-普通攻击"
                post_delay: 0.1
                repeat: 20

          - states: "[叶瞬光-青溟剑势-白]{4,4}"
            interrupt_states: "[叶瞬光-青溟剑势-白]{3,3}"
            operations:
              - op_name: "设置状态"
                state: "自定义-无视闪光"
                seconds: 9
              - op_name: "设置状态"
                state: "自定义-动作不打断"
                seconds: 9
              - op_name: "按键-普通攻击"
                post_delay: 0.1
                repeat: 20

          - states: "[叶瞬光-青溟剑势-白]{3,3}"
            interrupt_states: "[叶瞬光-青溟剑势-白]{1,1}"
            operations:
              - op_name: "设置状态"
                state: "自定义-无视闪光"
                seconds: 9
              - op_name: "设置状态"
                state: "自定义-动作不打断"
                seconds: 9
              - op_name: "按键-特殊攻击"
                post_delay: 0.1
                repeat: 12
              - op_name: "按键-普通攻击"
                post_delay: 0.1
                repeat: 40

          - states: "[叶瞬光-青溟剑势-白]{1,1}"
            interrupt_states: "[叶瞬光-青溟剑势-白]{0,0}"
            operations:
              - op_name: "设置状态"
                state: "自定义-无视闪光"
                seconds: 9
              - op_name: "设置状态"
                state: "自定义-动作不打断"
                seconds: 9
              - op_name: "按键-普通攻击"
                post_delay: 0.1
                repeat: 20

          - states: "[叶瞬光-青溟剑势-白]{2,2} | [叶瞬光-青溟剑势-白]{5,5}"
            interrupt_states: "[叶瞬光-青溟剑势-白]{0,0} | [叶瞬光-明心境]{0,20}"
            operations:
              - op_name: "设置状态"
                state: "自定义-无视闪光"
                seconds: 9
              - op_name: "设置状态"
                state: "自定义-动作不打断"
                seconds: 9
              - op_name: "按键-普通攻击"
                post_delay: 0.1
                repeat: 20

      - states: "([叶瞬光-青溟剑势-白]{0,0} | [叶瞬光-明心境]{0,20}) & ![叶瞬光-青溟剑势-白]{6,6}"
        interrupt_states: "([叶瞬光-明心境]{0,0}) | [叶瞬光-明心境]{90,130}"
        operations:
          - op_name: "设置状态"
            state: "自定义-无视闪光"
            seconds: 9
          - op_name: "设置状态"
            state: "自定义-动作不打断"
            seconds: 9
          - operation_template: "叶瞬光-乱砍"
