name: Sync to CNB

on:
  push:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  sync:
    if: ${{ github.repository == 'OneDragon-Anything/ZenlessZoneZero-OneDragon' }}
    runs-on: ubuntu-latest
    steps:
      - name: Push to CNB
        env:
          CNB_TOKEN: ${{ secrets.CNB_GIT_TOKEN }}
        run: |
          git clone --bare "${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}.git" repository.git
          git -C repository.git remote add cnb "https://cnb:${CNB_TOKEN}@cnb.cool/OneDragon-Anything/ZenlessZoneZero-OneDragon.git"
          git -C repository.git push --force --prune cnb \
            '+refs/heads/*:refs/heads/*' \
            '+refs/tags/*:refs/tags/*'
